# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hub_pb2 as hub__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModbusHubStub:
    """ModbusHub owns every Modbus connection on the device. Applications declare
    what they need instead of opening their own links, so a device polled by two
    applications is still read once, and nothing can interleave frames on a bus.

    The hub deliberately speaks RAW REGISTERS. It does not scale, decode, or know
    anything about gain/sign/word order -- each client keeps its own, already
    field-validated decoding layer.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Subscribe = channel.stream_stream(
                '/modbushub.v1.ModbusHub/Subscribe',
                request_serializer=hub__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=hub__pb2.BlockUpdate.FromString,
                _registered_method=True)
        self.ReadBlock = channel.unary_unary(
                '/modbushub.v1.ModbusHub/ReadBlock',
                request_serializer=hub__pb2.ReadBlockRequest.SerializeToString,
                response_deserializer=hub__pb2.BlockUpdate.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/modbushub.v1.ModbusHub/Write',
                request_serializer=hub__pb2.WriteRequest.SerializeToString,
                response_deserializer=hub__pb2.WriteResult.FromString,
                _registered_method=True)
        self.WatchLinks = channel.unary_stream(
                '/modbushub.v1.ModbusHub/WatchLinks',
                request_serializer=hub__pb2.WatchLinksRequest.SerializeToString,
                response_deserializer=hub__pb2.LinkStatus.FromString,
                _registered_method=True)


class ModbusHubServicer:
    """ModbusHub owns every Modbus connection on the device. Applications declare
    what they need instead of opening their own links, so a device polled by two
    applications is still read once, and nothing can interleave frames on a bus.

    The hub deliberately speaks RAW REGISTERS. It does not scale, decode, or know
    anything about gain/sign/word order -- each client keeps its own, already
    field-validated decoding layer.
    """

    def Subscribe(self, request_iterator, context):
        """Subscribe declares the blocks a client wants and how often. The hub merges
        overlapping declarations across all clients, polls once, and streams the
        result back to every subscriber. Each SubscribeRequest replaces the
        client's previous declaration in full.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBlock(self, request, context):
        """ReadBlock answers a single block from cache, or from the device when
        `force` is set. Used for one-shot diagnostics, not for steady polling.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Write queues a write on the target link's request queue, ahead of polling.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchLinks(self, request, context):
        """WatchLinks streams link up/down transitions so clients can drive their own
        reconnect and fail-safe logic.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModbusHubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Subscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=hub__pb2.SubscribeRequest.FromString,
                    response_serializer=hub__pb2.BlockUpdate.SerializeToString,
            ),
            'ReadBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBlock,
                    request_deserializer=hub__pb2.ReadBlockRequest.FromString,
                    response_serializer=hub__pb2.BlockUpdate.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=hub__pb2.WriteRequest.FromString,
                    response_serializer=hub__pb2.WriteResult.SerializeToString,
            ),
            'WatchLinks': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchLinks,
                    request_deserializer=hub__pb2.WatchLinksRequest.FromString,
                    response_serializer=hub__pb2.LinkStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'modbushub.v1.ModbusHub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('modbushub.v1.ModbusHub', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModbusHub:
    """ModbusHub owns every Modbus connection on the device. Applications declare
    what they need instead of opening their own links, so a device polled by two
    applications is still read once, and nothing can interleave frames on a bus.

    The hub deliberately speaks RAW REGISTERS. It does not scale, decode, or know
    anything about gain/sign/word order -- each client keeps its own, already
    field-validated decoding layer.
    """

    @staticmethod
    def Subscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/modbushub.v1.ModbusHub/Subscribe',
            hub__pb2.SubscribeRequest.SerializeToString,
            hub__pb2.BlockUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modbushub.v1.ModbusHub/ReadBlock',
            hub__pb2.ReadBlockRequest.SerializeToString,
            hub__pb2.BlockUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modbushub.v1.ModbusHub/Write',
            hub__pb2.WriteRequest.SerializeToString,
            hub__pb2.WriteResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/modbushub.v1.ModbusHub/WatchLinks',
            hub__pb2.WatchLinksRequest.SerializeToString,
            hub__pb2.LinkStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
